spring:
  application:
    name: user-center
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://43.142.43.79:3306/user_center
      username: dogyupi
      password: yupi666
  #失效时间
  session:
    timeout: 86400
server:
  address: 0.0.0.0